# Generated by Django 4.2.5 on 2023-09-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0004_alter_order_shipping_address_alter_pucharse_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='from_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_address', to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_address', to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='with_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
