# Generated by Django 4.2.5 on 2023-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_shipping_address_order_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='with_shipping',
            field=models.BooleanField(),
        ),
    ]
