# Generated by Django 4.2.5 on 2023-09-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_with_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pucharse',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pucharses', to='orders.order'),
        ),
    ]
