# Generated by Django 4.2.5 on 2023-10-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_with_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='with_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
