# Generated by Django 4.2.5 on 2023-10-18 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_purchase_delete_pucharse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='deliverer',
        ),
        migrations.AddField(
            model_name='shipping',
            name='deliverer',
            field=models.ManyToManyField(related_name='shipping', to=settings.AUTH_USER_MODEL),
        ),
    ]
