# Generated by Django 4.2.5 on 2023-10-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_shipping_name_remove_shipping_deliverer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='deliverer',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='name',
        ),
    ]
