# Generated by Django 4.2.5 on 2023-10-20 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_alter_order_order_status_alter_refund_costumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund', to=settings.AUTH_USER_MODEL),
        ),
    ]
