# Generated by Django 4.2.5 on 2023-10-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_refund_accepted_alter_refund_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('on_the_way', 'On the way'), ('delivered', 'Delivered'), ('pending_refund', 'Pending refund'), ('refund_not_accepted', 'Refund not accepted'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
    ]
