# Generated by Django 4.2.5 on 2023-09-28 01:00

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=products.models.product_img_path),
        ),
    ]
