# Generated by Django 4.2.5 on 2023-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
