# Generated by Django 4.2.5 on 2023-10-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_created_at_alter_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
