# Generated by Django 4.2.5 on 2023-10-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='total',
        ),
    ]
