# Generated by Django 4.2.5 on 2023-10-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deliverer',
        ),
    ]
