# Generated by Django 4.2.5 on 2023-10-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_deliverer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apartment_address',
            new_name='appartment_address',
        ),
    ]
